version: "3"
networks:
  mysql:
services:
  db1:
    container_name: db1
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db_1:/var/lib/mysql
      - ./s1.cnf:/etc/mysql/my.cnf
    networks:
      mysql:

  db2:
    container_name: db2
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db_2:/var/lib/mysql
      - ./s2.cnf:/etc/mysql/my.cnf
    networks:
      mysql:

  db3:
    container_name: db3
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db_3:/var/lib/mysql
      - ./s3.cnf:/etc/mysql/my.cnf
    networks:
      mysql:
